[project]
name = "tks"
version = "0.1.0"
authors = [{name="Hunter Logan", email="_@piccoloser.com"}]
description = "tkinter superset"
license = {file = "LICENSE"}
readme = "README.md"

[tool.black]
line-length = 119